[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:backend]
command=python main.py
directory=/app
environment=PORT="8000"
stdout_logfile=/app/frontend-server/public/fastapi.log
stdout_logfile_maxbytes=0
stderr_logfile=/app/frontend-server/public/fastapi.log
stderr_logfile_maxbytes=0
autorestart=true

[program:frontend]
command=node server.js
directory=/app/frontend-server
environment=PORT="3000",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
